#!/bin/sh
echo "#Autogenerated file, do not edit" > Kconfig
FILES=`ls`
for FILE in $FILES ; do
	if [ -d $FILE ] ; then
		echo "source board/$FILE/Kconfig" >> Kconfig
		echo "Found board: $FILE"
	fi
done
echo "Generated Kconfig for boards"
